# Site
name: "Shibe On Film"
title: "Shibe On Film"
description: "Today's images with a touch of yestrrday."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: 
google_analytics: 'UA-xxxxxxxx-1'
disqus:
mailchimp-list:
include: ["_pages"]
permalink: /:year/:month/:title/
email: 

# Authors
authors:
  jayden:
    name: Jayden
    display_name: Jayden
    avatar: 'assets/images/avatar.jpg'
    email: 
    web: https://www.squabbi.com/
    twitter: https://twitter.com/
    description: "Author of Memoirs, a Bootstrap Medium styled template available for Jekyll. You are currently previewing Jekyll template demo."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
